routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('lang/{language}', ['as'=>'lang.switch', 'uses'=>'LanguageController@switchLang']);

Route::group(['middleware'=>'language','prefix'=>Config::get('routeLang')], function(){
    Route::get('/', ['as'=>'home', 'uses'=>'GeneralController@index']);
    Route::get('/page/{name}', ['as'=>'page', 'uses'=>'GeneralController@page']);
    Route::get('/units/{id}', ['as'=>'units', 'uses'=>'GeneralController@unit']);

    Route::post('/calculate/{id}', ['as'=>'calculate', 'uses'=>'GeneralController@calculate']);
    Route::post('/proposal', ['as'=>'proposal', 'uses'=>'GeneralController@proposal']);
});

Route::group(['prefix'=>'dashboard', 'namespace'=>'Dashboard','middleware'=>'auth'],function(){
    //App::setlocale('ru');
    Route::get('/',['as'=>'dashboard', 'uses'=>'DashboardController@index']);
    Route::resource('users', 'UserController', ['except' => 'show']);
    Route::resource('units', 'UnitController', ['except' => 'show']);
    Route::resource('holidays', 'HolidayController', ['except' => 'show']);
    Route::resource('pages', 'PageController', ['except' => 'show']);
    Route::resource('options', 'OptionController', ['except' => 'show']);
    //Route::resource('proposals', 'ProposalController', ['except' => 'show']);
    Route::resource('priceindexes', 'PriceindexController', ['except' => 'show']);
    Route::resource('bankrates', 'BankrateController', ['except' => 'show']);
    Route::resource('minsalaries', 'MinsalaryController', ['except' => 'show']);
    Route::resource('minlifes', 'MinlifeController', ['except' => 'show']);
});

Route::group(['prefix'=>'datatable'],function(){
    Route::post('/getpriceindexes', ['as'=>'getpriceindexes', 'uses'=>'DatatableController@getPriceindexes']);
});

Route::get('/register',function(){
    return redirect(route('login'));
});

app/Bankrate.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Bankrate extends Model
{
    protected $dates = ['date'];

}

app/Http/Controllers/Dashboard/BankrateController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Bankrate;
use App\Http\Requests\StoreBankrateRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BankrateController extends Controller
{
    public function index(Request $request)
    {
        $models = Bankrate::where([['trash','=',false]])->orderby('date','DESC')->paginate(20);
        return view('dashboard.bankrate.index', [
                'models' => $models,
                'pagination_add' => $request->input(),
            ]);
    }

    public function create(Request $request)
    {
        return view('dashboard.bankrate.create', [
            ]);
    }

    public function store(StoreBankrateRequest $request)
    {
        $model = new Bankrate;
        $model->date = $request->date;
        $model->value = $request->value;
        $model->save();
        return redirect()->route('bankrates.index')
            ->with('flash_message', trans('cms.alert-create', ['name' => $model->name]));
    }

    public function show($id)
    {
    }

    public function edit($id)
    {
        $model = Bankrate::findOrFail($id);
        return view('dashboard.bankrate.edit', [
                'model'=>$model,
            ]);
    }

    public function update(StoreBankrateRequest $request, $id)
    {
        $model = Bankrate::findOrFail($id);
        $model->date = $request->date;
        $model->value = $request->value;
        $model->save();
        return redirect()->route('bankrates.index')
            ->with('flash_message', trans('cms.alert-update', ['name' => $model->name]));
    }

    public function destroy(Request $request, $id)
    {
        $model = Bankrate::findOrFail($id);
        $model->trash = true;
        $model->save();
        //$model->delete();
        return redirect(route('bankrates.index'))->with('error_message', trans('cms.alert-remove', ['name' => $model->name]));
    }

}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public function index()
    {
        return View('dashboard.index');
    }
}

app/Http/Controllers/Dashboard/HolidayController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Holiday;
use App\Http\Requests\StoreHolidayRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class HolidayController extends Controller
{
    public function index(Request $request)
    {
        $models = Holiday::where([['trash','=',false]])->orderby('date','DESC')->paginate(20);
        return view('dashboard.holiday.index', [
                'models' => $models,
                'pagination_add' => $request->input(),
            ]);
    }

    public function create(Request $request)
    {
        $types = (object)[trans('calculator.holidaytype0'), trans('calculator.holidaytype1'), trans('calculator.holidaytype2')];
        return view('dashboard.holiday.create', [
                'types' => $types,
            ]);
    }

    public function store(StoreHolidayRequest $request)
    {
        $model = new Holiday;
        $model->name = $request->name;
        $model->date = $request->date;
        $model->type = $request->type;
        $model->transfer = $request->transfer;
        $model->save();
        return redirect()->route('holidays.index')
            ->with('flash_message', trans('cms.alert-create', ['name' => $model->name]));
    }

    public function show($id)
    {
    }

    public function edit($id)
    {
        $types = (object)[trans('calculator.holidaytype0'), trans('calculator.holidaytype1'), trans('calculator.holidaytype2')];
        $model = Holiday::findOrFail($id);
        return view('dashboard.holiday.edit', [
                'model'=>$model,
                'types' => $types,
            ]);
    }

    public function update(StoreHolidayRequest $request, $id)
    {
        $model = Holiday::findOrFail($id);
        $model->name = $request->name;
        $model->date = $request->date;
        $model->type = $request->type;
        $model->transfer = $request->transfer;
        $model->save();
        return redirect()->route('holidays.index')
            ->with('flash_message', trans('cms.alert-update', ['name' => $model->name]));
    }

    public function destroy(Request $request, $id)
    {
        $model = Holiday::findOrFail($id);
        $model->trash = true;
        $model->save();
        //$model->delete();
        return redirect(route('holidays.index'))->with('error_message', trans('cms.alert-remove', ['name' => $model->name]));
    }

}

app/Http/Controllers/Dashboard/MinlifeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Minlife;
use App\Http\Requests\StoreMinlifeRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class MinlifeController extends Controller
{
    public function index(Request $request)
    {
        $models = Minlife::where([['trash','=',false]])->orderby('year','DESC')->orderby('month','DESC')->paginate(20);
        return view('dashboard.minlife.index', [
                'models' => $models,
                'pagination_add' => $request->input(),
            ]);
    }

    public function create(Request $request)
    {
        $monthes = [];
        for ($i=1; $i < 13; $i++) { 
            $monthes[$i] = trans('calculator.month'.$i);
        }
        $years = [];
        for ($i=1999; $i < ((int)now()->format('Y'))+2; $i++) { 
            $years[$i] = $i;
        }
        return view('dashboard.minlife.create', [
                'monthes' => $monthes,
                'years' => $years,
            ]);
    }

    public function store(StoreMinlifeRequest $request)
    {
        $model = new Minlife;
        $model->month = $request->month;
        $model->year = $request->year;
        $model->value_baby = $request->value_baby;
        $model->value_child = $request->value_child;
        $model->value_worker = $request->value_worker;
        $model->value_invalid = $request->value_invalid;
        $model->value = $request->value;
        $model->save();
        return redirect()->route('minlifes.index')
            ->with('flash_message', trans('cms.alert-create', ['name' => $model->name]));
    }

    public function show($id)
    {
    }

    public function edit($id)
    {
        $monthes = [];
        for ($i=1; $i < 13; $i++) { 
            $monthes[$i] = trans('calculator.month'.$i);
        }
        $years = [];
        for ($i=1999; $i < ((int)now()->format('Y'))+2; $i++) { 
            $years[$i] = $i;
        }
        $model = Minlife::findOrFail($id);
        return view('dashboard.minlife.edit', [
                'model'=>$model,
                'monthes' => $monthes,
                'years' => $years,
            ]);
    }

    public function update(StoreMinlifeRequest $request, $id)
    {
        $model = Minlife::findOrFail($id);
        $model->month = $request->month;
        $model->year = $request->year;
        $model->value_baby = $request->value_baby;
        $model->value_child = $request->value_child;
        $model->value_worker = $request->value_worker;
        $model->value_invalid = $request->value_invalid;
        $model->value = $request->value;
        $model->save();
        return redirect()->route('minlifes.index')
            ->with('flash_message', trans('cms.alert-update', ['name' => $model->name]));
    }

    public function destroy(Request $request, $id)
    {
        $model = Minlife::findOrFail($id);
        $model->trash = true;
        $model->save();
        //$model->delete();
        return redirect(route('minlifes.index'))->with('error_message', trans('cms.alert-remove', ['name' => $model->name]));
    }

}

app/Http/Controllers/Dashboard/MinsalaryController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Minsalary;
use App\Http\Requests\StoreMinsalaryRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class MinsalaryController extends Controller
{
    public function index(Request $request)
    {
        $models = Minsalary::where([['trash','=',false]])->orderby('year','DESC')->orderby('month','DESC')->paginate(20);
        return view('dashboard.minsalary.index', [
                'models' => $models,
                'pagination_add' => $request->input(),
            ]);
    }

    public function create(Request $request)
    {
        $monthes = [];
        for ($i=1; $i < 13; $i++) { 
            $monthes[$i] = trans('calculator.month'.$i);
        }
        $years = [];
        for ($i=1999; $i < ((int)now()->format('Y'))+2; $i++) { 
            $years[$i] = $i;
        }
        return view('dashboard.minsalary.create', [
                'monthes' => $monthes,
                'years' => $years,
            ]);
    }

    public function store(StoreMinsalaryRequest $request)
    {
        $model = new Minsalary;
        $model->month = $request->month;
        $model->year = $request->year;
        $model->value = $request->value;
        $model->save();
        return redirect()->route('minsalaries.index')
            ->with('flash_message', trans('cms.alert-create', ['name' => $model->name]));
    }

    public function show($id)
    {
    }

    public function edit($id)
    {
        $monthes = [];
        for ($i=1; $i < 13; $i++) { 
            $monthes[$i] = trans('calculator.month'.$i);
        }
        $years = [];
        for ($i=1999; $i < ((int)now()->format('Y'))+2; $i++) { 
            $years[$i] = $i;
        }
        $model = Minsalary::findOrFail($id);
        return view('dashboard.minsalary.edit', [
                'model'=>$model,
                'monthes' => $monthes,
                'years' => $years,
            ]);
    }

    public function update(StoreMinsalaryRequest $request, $id)
    {
        $model = Minsalary::findOrFail($id);
        $model->month = $request->month;
        $model->year = $request->year;
        $model->value = $request->value;
        $model->save();
        return redirect()->route('minsalaries.index')
            ->with('flash_message', trans('cms.alert-update', ['name' => $model->name]));
    }

    public function destroy(Request $request, $id)
    {
        $model = Minsalary::findOrFail($id);
        $model->trash = true;
        $model->save();
        //$model->delete();
        return redirect(route('minsalaries.index'))->with('error_message', trans('cms.alert-remove', ['name' => $model->name]));
    }

}

app/Http/Controllers/Dashboard/OptionController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Option;
use App\Http\Requests\StoreOptionRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OptionController extends Controller
{
    // public function __construct() {
    //     parent::__construct();
    //     $this->data['icon'] = 'icon-database-export';
    //     $this->data['title'] = trans('cms.export-data');
    //     array_push($this->data['breadcrumbs'] , ["title" => $this->data['title'],"url" => route('acts.index')]);
    // }

    public function index(Request $request)
    {
        $models = Option::where([['trash','=',false]])->orderby('id')->paginate(20);
        return view('dashboard.option.index', [
                'models' => $models,
                'pagination_add' => $request->input(),
            ]);
    }

    public function create(Request $request)
    {
        return view('dashboard.option.create', [
            ]);
    }

    public function store(StoreOptionRequest $request)
    {
        $model = new Option;
        $model->name = $request->name;
        $model->value = $request->value;
        $model->save();
        return redirect()->route('options.index')
            ->with('flash_message', trans('cms.alert-create', ['name' => $model->name]));
    }

    public function show($id)
    {
    }

    public function edit($id)
    {
        $model = Option::findOrFail($id);
        return view('dashboard.option.edit', [
                'model'=>$model,
            ]);
    }

    public function update(StoreOptionRequest $request, $id)
    {
        $model = Option::findOrFail($id);
        $model->name = $request->name;
        $model->value = $request->value;
        $model->save();
        return redirect()->route('options.index')
            ->with('flash_message', trans('cms.alert-update', ['name' => $model->name]));
    }

    public function destroy(Request $request, $id)
    {
        $model = Option::findOrFail($id);
        $model->trash = true;
        $model->save();
        //$model->delete();
        return redirect(route('options.index'))->with('error_message', trans('cms.alert-remove', ['name' => $model->name]));
    }

}

app/Http/Controllers/Dashboard/PageController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Page;
use App\Http\Requests\StorePageRequest;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PageController extends Controller
{
    public function index(Request $request)
    {
        $models = Page::where([['trash','=',false]])->orderby('id')->paginate(20);
        return view('dashboard.page.index', [
                'models' => $models,
                'pagination_add' => $request->input(),
            ]);
    }

    public function create(Request $request)
    {
        return view('dashboard.page.create', [
            ]);
    }

    public function store(StorePageRequest $request)
    {
        $model = new Page;
        $model->name = $request->name;
        $model->slug = $request->slug;
        $model->content = $request->content ? $request->content : '';
        $model->save();
        return redirect()->route('pages.index')
            ->with('flash_message', trans('cms.alert-create', ['name' => $model->name]));
    }

    public function show($id)
    {
    }

    public function edit($id)
    {
        $model = Page::findOrFail($id);
        return view('dashboard.page.edit', [
                'model'=>$model,
            ]);
    }

    public function update(StorePageRequest $request, $id)
    {
        $model = Page::findOrFail($id);
        $model->name = $request->name;
        $model->slug = $request->slug;
        $model->content = $request->content ? $request->content : '';
        $model->save();
        return redirect()->route('pages.index')
            ->with('flash_message', trans('cms.alert-update', ['name' => $model->name]));
    }

    public function destroy(Request $request, $id)
    {
        $model = Page::findOrFail($id);
        $model->trash = true;
        $model->save();
        //$model->delete();
        return redirect(route('pages.index'))->with('error_message', trans('cms.alert-remove', ['name' => $model->name]));
    }

}

resources/views/dashboard/bankrate/create.blade.php
@extends('layouts.admin')

@section('content')

{{ Form::open(array('url' => 'dashboard/bankrates')) }}
    <h1 class="mb-5">{{trans('calculator.bankrates')}} - {{trans('calculator.create')}}</h1>
    <div class="form-group">
        {{ Form::label('date', 'Дата', ['class'=>'small text-muted font-italic']) }}
        {{ Form::date('date', null, array('class' => 'form-control'. ($errors->has('date') ? ' is-invalid' : '' ))) }}
        @if($errors->has('date'))
            @foreach ($errors->get('date') as $message)
                <div class="invalid-feedback">{{ $message }}</div>
            @endforeach
        @endif
    </div>
    <div class="form-group">
        {{ Form::label('value', 'Значение', ['class'=>'small text-muted font-italic']) }}
        {{ Form::number('value', null, array('step'=>'0.01', 'class' => 'form-control'. ($errors->has('value') ? ' is-invalid' : '' ))) }}
        @if($errors->has('value'))
            @foreach ($errors->get('value') as $message)
                <div class="invalid-feedback">{{ $message }}</div>
            @endforeach
        @endif
    </div>
    <button type="submit" id="submit" class="btn btn-success mt-3" title="Save"><i class="fa fa-save fa-fw"></i></button>

{{ Form::close() }}

@endsection

resources/views/dashboard/bankrate/edit.blade.php
@extends('layouts.admin')

@section('content')

{{ Form::model($model, array('route' => array('bankrates.update', $model->id), 'method' => 'PUT')) }}
    <h1 class="mb-5">{{trans('calculator.bankrates')}} - {{trans('calculator.edit')}} (<span class="font-weight-bold">{{$model->date->format("d.m.Y")}}</span>)</h1>
    <div class="form-group">
        {{ Form::label('date', 'Дата', ['class'=>'small text-muted font-italic']) }}
        {{ Form::date('date', $model->date, array('class' => 'form-control'. ($errors->has('date') ? ' is-invalid' : '' ))) }}
        @if($errors->has('date'))
            @foreach ($errors->get('date') as $message)
                <div class="invalid-feedback">{{ $message }}</div>
            @endforeach
        @endif
    </div>
    <div class="form-group">
        {{ Form::label('value', 'Значение', ['class'=>'small text-muted font-italic']) }}
        {{ Form::number('value', null, array('step'=>'0.01', 'class' => 'form-control'. ($errors->has('value') ? ' is-invalid' : '' ))) }}
        @if($errors->has('value'))
            @foreach ($errors->get('value') as $message)
                <div class="invalid-feedback">{{ $message }}</div>
            @endforeach
        @endif
    </div>
    <button type="submit" id="submit" class="btn btn-success mt-3" title="Save"><i class="fa fa-save fa-fw"></i></button>

{{ Form::close() }}

@endsection

resources/views/dashboard/bankrate/index.blade.php
@extends('layouts.admin')

@section('content')
    <h1 class="mb-5">{{trans('calculator.bankrates')}}</h1>
    <table class="table table-striped w-100">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>Value</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach($models as $key => $model)
            <tr>
                <td class="text-center">{{$model->id}}</td>
                <td class="text-center">@if($model->date){{$model->date->format('Y-m-d')}}@endif</td>
                <td class="text-center">{{$model->value}}</td>
                <td class="text-center">
                    <div class="btn-group">
                        <a href="{{route('bankrates.edit',$model->id)}}" class="btn btn-info btn-sm" title="Змінити"><i class="fa fa-pencil fa-fw"></i></a>
                        <a href="{{route('bankrates.destroy',$model->id)}}" class="btn btn-danger btn-sm btn-remove" data-toggle="modal" data-target="#removeModal" title="Видалити"><i class="fa fa-trash-o fa-fw"></i></a>
                   </div>                    
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="d-flex mt-3 justify-content-between">
        <a href="{{ route('bankrates.create') }}" class="btn btn-success" title="{{trans('cms.btn-append')}}"><i class="fa fa-fw fa-plus"></i></a>
        {{ $models->appends($pagination_add)->links() }}
    </div>

@endsection