routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('lang/{language}', ['as'=>'lang.switch', 'uses'=>'LanguageController@switchLang']);

Route::group(['middleware'=>'language','prefix'=>Config::get('routeLang')], function(){
    Route::get('/', ['as'=>'home', 'uses'=>'GeneralController@index']);
    Route::get('/page/{name}', ['as'=>'page', 'uses'=>'GeneralController@page']);
    Route::get('/units/{id}', ['as'=>'units', 'uses'=>'GeneralController@unit']);

    Route::post('/calculate/{id}', ['as'=>'calculate', 'uses'=>'GeneralController@calculate']);
    Route::post('/proposal', ['as'=>'proposal', 'uses'=>'GeneralController@proposal']);
});

Route::group(['prefix'=>'dashboard', 'namespace'=>'Dashboard','middleware'=>'auth'],function(){
    //App::setlocale('ru');
    Route::get('/',['as'=>'dashboard', 'uses'=>'DashboardController@index']);
    Route::resource('users', 'UserController', ['except' => 'show']);
    Route::resource('units', 'UnitController', ['except' => 'show']);
    Route::resource('holidays', 'HolidayController', ['except' => 'show']);
    Route::resource('pages', 'PageController', ['except' => 'show']);
    Route::resource('options', 'OptionController', ['except' => 'show']);
    //Route::resource('proposals', 'ProposalController', ['except' => 'show']);
    Route::resource('priceindexes', 'PriceindexController', ['except' => 'show']);
    Route::resource('bankrates', 'BankrateController', ['except' => 'show']);
    Route::resource('minsalaries', 'MinsalaryController', ['except' => 'show']);
    Route::resource('minlifes', 'MinlifeController', ['except' => 'show']);
});

Route::group(['prefix'=>'datatable'],function(){
    Route::post('/getpriceindexes', ['as'=>'getpriceindexes', 'uses'=>'DatatableController@getPriceindexes']);
});

Route::get('/register',function(){
    return redirect(route('login'));
});

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="{{app()->getLocale()}}">

<head>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png" href="/assets/img/favicon.png" />
    <title>{{ config('app.name') }}</title>
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;subset=cyrillic" rel="stylesheet">
    <link href="/assets/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/assets/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="/assets/lib/datatables/datatables.min.css" rel="stylesheet" type="text/css"/>    
    <link href="/css/common.css" rel="stylesheet" type="text/css">
    <link href="/css/admin.css" rel="stylesheet" type="text/css">
</head>

<body>

    <div class="bg-blue p-3 d-flex align-items-center justify-content-between">
        <div class="img-wrap"><a href="{{route('home')}}"><img src="/assets/img/activeLex_logo_calculator(ukr).png" alt=""></a></div>
        <div>
            <a href="#" class="text-white" data-toggle="modal" data-target="#exampleModal"><i class="fa fa-2x fa-fw fa-long-arrow-right"></i></a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">{{ csrf_field() }}</form>
        </div>
    </div>

    <div class="content-wrapper d-flex">
        <aside>
            <ul>
                <li><a href="{{route('dashboard')}}"><i class="fa fa-fw fa-dashboard"></i> {{trans('calculator.dashboard')}}</a></li>
                <li><a href="{{route('users.index')}}"><i class="fa fa-fw fa-user"></i> {{trans('calculator.users')}}</a></li>
                <li><a href="{{route('units.index')}}"><i class="fa fa-fw fa-desktop"></i> {{trans('calculator.units')}}</a></li>
                <li><a href="{{route('pages.index')}}"><i class="fa fa-fw fa-file"></i> {{trans('calculator.pages')}}</a></li>
                <li><a href="{{route('options.index')}}"><i class="fa fa-fw fa-cog"></i> {{trans('calculator.options')}}</a></li>
                <li><a href="#"><i class="fa fa-fw fa-envelope"></i> {{trans('calculator.proposals')}}</a></li>
                <hr>
                <li><a href="{{route('holidays.index')}}"><i class="fa fa-fw fa-calendar"></i> {{trans('calculator.holidays')}}</a></li>
                <li><a href="{{route('priceindexes.index')}}"><i class="fa fa-fw fa-shopping-cart"></i> {{trans('calculator.priceindexes')}}</a></li>
                <li><a href="{{route('bankrates.index')}}"><i class="fa fa-fw fa-university"></i> {{trans('calculator.bankrates')}}</a></li>
                <li><a href="{{route('minsalaries.index')}}"><i class="fa fa-fw fa-credit-card"></i> {{trans('calculator.minsalaries')}}</a></li>
                <li><a href="{{route('minlifes.index')}}"><i class="fa fa-fw fa-cutlery"></i> {{trans('calculator.minlifes')}}</a></li>
            </ul>
        </aside>
        <div class="p-5 content-area">
            <!-- Alerts -->
            @if(Session::has('flash_message'))
                <div class="alert alert-success alert-styled-left alert-arrow-left alert-dismissible mt-3">
                    <button type="button" class="close" data-dismiss="alert"><span>×</span></button>
                    {!! session('flash_message') !!}
                </div>                    
            @endif
            @if(Session::has('error_message'))
                <div class="alert alert-warning alert-styled-left alert-arrow-left alert-dismissible mt-3">
                    <button type="button" class="close" data-dismiss="alert"><span>×</span></button>
                    {!! session('error_message') !!}
                </div>
            @endif
            <!-- /alerts -->
            @section('content')
            @show
        </div>
    </div>
    <footer class="text-center">
        Admin area of calculators
    </footer>

    <!-- Logout Modal-->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h6 class="modal-title" id="exampleModalLabel">Выход</h6>
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <a class="btn btn-primary" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Выход</a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">@csrf</form>
                    <button class="btn btn-light" type="button" data-dismiss="modal">Отмена</button>
                </div>
            </div>
        </div>
    </div>
    <!-- Remove Modal-->
    <div id="removeModal" class="modal fade" tabindex="-1">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header bg-danger text-white">
                                <h6 class="modal-title">Удаление элемента</h6>
                                <button type="button" class="close text-white" data-dismiss="modal">&times;</button>
                            </div>

                            <div class="modal-body" id="remove-modal-body">
                                Вы уверены, что хотите удалить элемент без возможности восстановления?
                            </div>
                            <form id="remove-form" action="{{ route('logout') }}" method="POST" style="display: none;">@csrf
                            <input name="_method" type="hidden" value="DELETE"><input name="_action" type="hidden" value="DELETE"></form>
                            <div class="modal-footer">
                                <button type="button" class="btn bg-danger text-white" onclick="document.getElementById('remove-form').submit()">Удалить</button>
                                <button type="button" class="btn btn-light" data-dismiss="modal">Отмена</button>
                            </div>
                        </div>
                    </div>
                </div>

    @section('modals')
    @show

    <!-- Bootstrap core JavaScript-->
    <script src="/assets/lib/jquery/jquery.min.js"></script>
    <script src="/assets/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="/assets/lib/bootbox/bootbox.min.js"></script>
    <script type="text/javascript" src="/assets/lib/datatables/datatables.min.js"></script>
    <script type="text/javascript" src="/assets/lib/tinymce/tinymce.min.js"></script>
    <script>tinymce.init({selector:'.tinymce',height : "400",plugins: "code",});</script>
    <script src="/js/common.js"></script>

    @section('scripts')
    @show

</body>

</html>

resources/views/layouts/footer.blade.php
<div class="container">
    <div class="footer-area bg-blue">
        <div class="row">
            <div class="col-lg-6">
                <h2 class="mb-5">Контакти</h2>
                <ul class="contacts mb-5">
                    <li class="mb-3 @getoption('showphone')">
                        <div class="rounded-circle p-2 bg-light-blue contact-thumb"><i class="fa fa-fw fa-2x fa-phone"></i></div>
                        <div>@getoption('phone')</div>
                    </li>
                    <li class="mb-3 @getoption('showemail')">
                        <div class="rounded-circle p-2 bg-light-blue contact-thumb"><i class="fa fa-fw fa-2x fa-envelope"></i></div>
                        <div>@getoption('email')</div>
                    </li>
                    <li class="@getoption('showadress')">
                        <div class="rounded-circle p-2 bg-light-blue contact-thumb"><i class="fa fa-fw fa-2x fa-map-marker"></i></div>
                        <div>@getoption('adress')</div>
                    </li>
                </ul>
                <h2 class="mb-5">Ми в соц. мережах</h2>
                <ul class="social">
                    <li><a href="@getoption('facebook')"><i class="fa fa-2x fa-facebook mr-2"></i></a></li>
                    <li><a href="@getoption('twitter')"><i class="fa fa-2x fa-twitter mr-2"></i></a></li>
                    <li><a href="@getoption('linkedin')"><i class="fa fa-2x fa-linkedin mr-2"></i></a></li>
                </ul>
            </div>
            <div class="col-lg-6">
                <h3 class="mt-5 mb-5">Є питання або пропозиції? Напишіть нам</h3>
                <form id="send-form">
                    <div class="row">
                        <div class="col-md-6">
                            <input name="name" id="name" type="text" class="my-form-control" placeholder="Ім'я" required>
                        </div>
                        <div class="col-md-6">
                            <input name="email" id="email" type="email" class="my-form-control" placeholder="Email" required>
                        </div>
                        <div class="col-md-12 mt-3">
                            <textarea name="content" id="content" cols="30" rows="5" class="my-form-control" placeholder="Повідомлення" required></textarea>
                        </div>
                    </div>
                    <div class="text-right mt-3"><button class="btn btn-red">Надіслати <i class="fa fa-long-arrow-right"></i></button></div>
                </form>
            </div>
        </div>
    </div>
    <div class="bottom-line">© Activelex 2018</div>
</div>

<div id = "GotoTop" ><i class="fa fa-fw fa-angle-up fa-2x" aria-hidden="true"></i></div>

@include('modals.sended')

    <!-- Bootstrap core JavaScript-->
    <script src="/assets/lib/jquery/jquery.min.js"></script>
    <script src="/assets/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="/assets/lib/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script src="/assets/lib/bootstrap-datepicker/locales/bootstrap-datepicker.uk.min.js" charset="UTF-8"></script>
    <script src="/assets/lib/printme/jquery-printme.js"></script>
    <script src="/js/common.js"></script>
<script>
$(document).ready(function(){
    $("#send-form").submit(function(e){
        e.preventDefault();
        $('#name').val('');
        $('#email').val('');
        $('#content').val('');
        $.ajax({
            url: '{{route('proposal')}}',
            type: 'POST',
            dataType : "json",
            headers: { 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
            beforeSend: function() {
            },
            success: function (data) {
                console.log(data);
                $("#sended").click();
            },
            error: function(){
                console.log('ajax-error');
            }
        });

        //console.log($('meta[name="csrf-token"]').attr('content'));
    });
});
</script>

    @section('scripts')
    @show
    @section('scripts2')
    @show

    </div>
</body>

</html>

resources/views/layouts/header.blade.php
<!DOCTYPE html>
<html lang="{{app()->getLocale()}}">

<head>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png" href="/assets/img/favicon.png" />
    <title>{{ config('app.name') }}</title>
    <link href="https://fonts.googleapis.com/css?family=Fira+Sans:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&amp;subset=cyrillic" rel="stylesheet">
    <link href="/assets/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link id="bsdp-css" href="/assets/lib/bootstrap-datepicker/css/bootstrap-datepicker3.min.css" rel="stylesheet">
    <link href="/assets/lib/bootstrap/css/bootstrap-hexa.css" rel="stylesheet">
    <link href="/assets/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="/css/common.css" rel="stylesheet" type="text/css">
</head>

<body>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-112604254-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-112604254-3');
</script>
    <div class="container">
        <div class="topline">
            <div class="img-wrap"><a href="{{route('home')}}"><img src="/assets/img/activeLex_logo_calculator(ukr).png" alt=""></a></div>
            @include('elements.switcher')
            <ul class="social">
                <li><a href="@getoption('facebook')"><i class="fa fa-2x fa-facebook mr-2"></i></a></li>
                <li><a href="@getoption('twitter')"><i class="fa fa-2x fa-twitter mr-2"></i></a></li>
                <li><a href="@getoption('linkedin')"><i class="fa fa-2x fa-linkedin mr-2"></i></a></li>
            </ul>
        </div>
    </div>
    <div class="menu text-center bg-blue">
        <div class="container">
            <button class="mobil-button"><i class="fa fa-reorder"></i></button>
            <ul class="inner-menu">
                <li><a href="{{route('home')}}">{{trans('calculator.home')}}</a></li>
                <li><a href="{{route('page','about')}}">{{trans('calculator.company')}}</a></li>
                {{--<li><a href="{{route('page','products')}}">{{trans('calculator.products')}}</a></li>--}}
                <li><a href="http://start.activelex.com/">{{trans('calculator.products')}}</a></li>
                {{--<li><a href="{{route('page','news')}}">{{trans('calculator.news')}}</a></li>--}}
                <li><a href="https://lexinform.com.ua/">{{trans('calculator.news')}}</a></li>
            </ul>
        </div>
    </div>

resources/views/layouts/layout.blade.php
@include('layouts.header')

    <div class="container">
        <div class="content-area bg-gray">
            @section('content')
            @show
        </div>
    </div>

@include('layouts.footer')